server:
  port: 8000

spring:
  application:
    name: cloud-order-openFeign-server #服务名称

eureka:
  client:
    # eureka注册中心地址配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/    #集群版
# 设置feign客户端超时时间（open feign默认支持ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源的所需时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别具体监控那个接口
    com.ys.springcloud.service.PaymentFeignService: debug