server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service #服务名称

eureka:
  client:
    # 表示是否将自己注册进eurekaServer注册中心，true-注入
      register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，默认true，但节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true
    # eureka注册中心地址配置
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/
    # 隐藏主机IP的别名
  instance:
    instance-id: hystrixPayment8001
    prefer-ip-address: true

